services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=http://localhost:3000
    healthcheck:
      disable: true

volumes:
  ollama_data:
